# Floyd-Warshall Algorithm for the SPP

In [29]:
import numpy as np
import networkx as nx

Floyd-Warshall's algorithm is useful for the Shortest Path Problem in order to find the shortest path from all vertices $s$ to all other vertices $t$. The time complexity is $O(n^3)$ as if we apply Dijkstra's algorithm from each vertex, but this algorithm can also be used in case of negative costs and is able to identify possible negative-cost cycles. However, in case of negative cycles, the algorithm stop, throwing an exception.

The algorithm makes use of two matrices $n \times n$, with $n$ the nummber of nodes:
* Distance matrix, containing the shortest distances between a pair of nodes, if exists a path for theme
* Predecessor matrix, showing the predecessor of a given node in the path for theme

In [42]:
def floyd_warshall(G):
    #useful variables of the graph given in input
    node_list = list(G.nodes)
    edge_list = list(G.edges)

    #number of nodes
    n = len(node_list)
    #number of edges
    m = len(edge_list)

    #sort the list of nodes in ascending order
    node_list.sort()

    #distances matrix
    DM = np.zeros(shape=(4, 4))
    #predecessor matrix
    PM = np.zeros(shape=(4, 4))

    #initialize the values for the two matrixes
    for i, node_i in enumerate(node_list):
        for j, node_j in enumerate(node_list):
            #assign node i to the predecessor matrix while comparing i-j
            PM[i][j] = node_i
            try:
                if i == j:
                    #assign distance 0 if i-j are the same node
                    DM[i][j] = 0
                else:
                    #assign the correct cost for node i-j if exists an arc between theme
                    DM[i][j] = G[node_i][node_j]['weight']
            except:
                #assign a big value in case does not exist an arce connecting i-j
                DM[i][j] = 99

    #loop for the triangular operations on h
    for h in range(n):
        for i in range(n):
            for j in range(n):
                if DM[i][h] + DM[h][j] < DM[i][j]:
                    #update values
                    DM[i][j] = DM[i][h] + DM[h][j]
                    PM[i][j] = PM[h][j]
        #check for negative cycles
        for i in range(n):
            if DM[i][i] < 0:
                raise Exception('Negative Cycles')

    return DM, PM


### Test

In [14]:
G = nx.DiGraph()
G.add_edge(1, 2, weight=2)
G.add_edge(1, 4, weight=-4)
G.add_edge(2, 4, weight=3)
G.add_edge(3, 1, weight=3)
G.add_edge(4, 2, weight=-1)
G.add_edge(4, 3, weight=4)

In [41]:
DM, PM = floyd_warshall(G)
print(DM)
print(PM)

[[ 0. -5.  0. -4.]
 [10.  0.  7.  3.]
 [ 3. -2.  0. -1.]
 [ 7. -1.  4.  0.]]
[[1. 4. 4. 1.]
 [3. 2. 4. 2.]
 [3. 4. 3. 1.]
 [3. 4. 4. 4.]]
